apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:1.6.15
        name: eclipse-mosquitto
        command: ["/bin/sh","-c"]
        args:
          - |
            sh /docker-entrypoint.sh
            /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
        envFrom:
          - configMapRef:
              name: mosquitto-env
        resources: {}
        volumeMounts:
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: create-password-file
            mountPath: /docker-entrypoint.sh
            subPath: docker-entrypoint.sh
          - name: mosquitto-data
            mountPath: /mosquitto/data
          - name: mosquitto-log
            mountPath: /mosquitto/log
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-configmap
        - name: create-password-file
          configMap:
            name: entrypoint
        - name: mosquitto-data
          emptyDir: {}
        - name: mosquitto-log
          emptyDir: {}
status: {}
