apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto-service
  name: mosquitto-service
spec:
  ports:
  - name: "1883"
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer
status:
  loadBalancer: {}
